# Generated by Django 4.0.3 on 2022-05-20 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=100)),
                ('cat_info', models.TextField()),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('cat_slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=100)),
                ('book_author', models.CharField(max_length=100)),
                ('book_info', models.TextField()),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('book_slug', models.SlugField()),
                ('book_pages', models.IntegerField()),
                ('book_cat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='books', to='kitap.category')),
            ],
        ),
    ]
