# Generated by Django 4.0.4 on 2022-05-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitap', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
